spring.application.name=blog
server.port=8032
spring.jpa.hibernate.ddl-auto=create
spring.datasource.username=postgres
spring.datasource.password=secret
management.server.port=9061
spring.datasource.url= jdbc:postgresql://localhost:5432/blog
spring.jpa.open-in-view=false
spring.messages.basename=i18n/messages
server.compression.enabled=true
spring.threads.virtual.enabled=true